services:
  - type: web
    name: societyman-erp-api
    env: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
